# Generated by Django 4.1.13 on 2024-05-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('footprint_id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement_unit', models.CharField(choices=[('Gramo', 'Gramo'), ('Kilogramo', 'Kilogramo'), ('Tonelada', 'Tonelada'), ('Mililitro', 'Mililitro'), ('Litro', 'Litro'), ('Metro cúbico', 'Metro cúbico'), ('Metro', 'Metro'), ('Centímetro', 'Centímetro'), ('Metro cuadrado', 'Metro cuadrado'), ('Palet', 'Palet'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Botella', 'Botella'), ('Barril', 'Barril'), ('Contenedor', 'Contenedor')], max_length=70, verbose_name='Measurement unit')),
                ('long', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Long')),
                ('high', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='High')),
                ('width', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Width')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Weight')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprint', to='authApp.product')),
            ],
        ),
    ]
