# Generated by Django 4.1.13 on 2024-05-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_discount_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Long')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='authApp.tax'),
            preserve_default=False,
        ),
    ]
